In [1]:
import numpy as np

In [37]:
component1 = np.array([[0,1,1],[0,1,1],[0,1,1]], dtype=np.uint8)
component2 = np.array([[0,1,0],[1,1,0],[1,1,0]], dtype=np.uint8)
def iou_metric(scores, output):  
    scores = scores.astype(np.bool)
    output = output.astype(np.bool)
    overlap = scores*output
    union = scores+output # Logical OR
    IOU = (overlap.sum())/(float(union.sum())+1e-10) 
    return IOU

In [3]:
x = np.array([[0,1,3],[0,2,1],[0,0,0]], dtype=np.uint8)

In [13]:
def create_masks(x):
    n_classes = 5
    mask = np.zeros((n_classes, x.shape[0], x.shape[1]))
    for c in range(n_classes):
        mask[c] = x == c
    print(mask)
    return mask

In [14]:
x_mask = create_masks(x)

[[[1. 0. 0.]
  [1. 0. 0.]
  [1. 1. 1.]]

 [[0. 1. 0.]
  [0. 0. 1.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 1. 0.]
  [0. 0. 0.]]

 [[0. 0. 1.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [11]:
truth = np.array([[0,1,1],[1,2,3],[2,1,2]], dtype=np.uint8)

In [16]:
t_mask = create_masks(truth)

[[[1. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 1. 1.]
  [1. 0. 0.]
  [0. 1. 0.]]

 [[0. 0. 0.]
  [0. 1. 0.]
  [1. 0. 1.]]

 [[0. 0. 0.]
  [0. 0. 1.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [27]:
iou_metric(x_mask[0], t_mask[0])

[[ True False False]
 [False False False]
 [False False False]]
[[ True False False]
 [ True False False]
 [ True  True  True]]


0.2

In [38]:
n_classes = 5
iou = [0]*n_classes
print(iou)
for c in range(n_classes):
    iou[c] = iou_metric(x_mask[c], t_mask[c])
print(iou)

[0, 0, 0, 0, 0]
[0.199999999996, 0.199999999996, 0.3333333333222222, 0.0, 0.0]


In [39]:
(.2+.2+.33)/5

0.146

In [40]:
z = np.zeros((64, 5))
out = np.mean(z, axis=0)

In [41]:
out

array([0., 0., 0., 0., 0.])

In [42]:
out.shape

(5,)